version: "3.7"

services:
  api:
    container_name: python-todos-api
    image: python
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - APP_PORT=8000
    depends_on:
      - mongo
    volumes:
      - .:/api
    ports: ["8080:8000"]
    tty: true

  mongo:
    container_name: mongo-db
    image: mongo
    volumes:
      - "./db:/data/db"
